#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh -dict system/blockMeshDict
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
cp -r 0.new 0 
runApplication simpleFoam

# run parallel
#runApplication decomposePar
#runApplication mpirun -np 7 scalarTransportFoam -parallel
#runApplication reconstructPar

